"""empty message

Revision ID: 4f5ada87142f
Revises: f1dacd342deb
Create Date: 2018-07-15 12:21:43.076425

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4f5ada87142f'
down_revision = 'f1dacd342deb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.drop_column('user', 'hash_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hash_password', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
