"""empty message

Revision ID: 8896b3f5d2e3
Revises: 
Create Date: 2018-07-13 09:09:23.599784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8896b3f5d2e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('krs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode', sa.String(length=10), nullable=False),
    sa.Column('nama', sa.String(length=25), nullable=False),
    sa.Column('sks', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('dosen', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mahasiswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('npm', sa.String(length=15), nullable=False),
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.Column('ttl', sa.String(length=75), nullable=False),
    sa.Column('kelamin', sa.String(length=20), nullable=False),
    sa.Column('alamat', sa.String(length=50), nullable=False),
    sa.Column('jurusan', sa.String(length=20), nullable=False),
    sa.Column('pa', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matkul',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode', sa.String(length=10), nullable=False),
    sa.Column('nama', sa.String(length=25), nullable=False),
    sa.Column('sks', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('dosen', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=50), nullable=False),
    sa.Column('user', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('matkul')
    op.drop_table('mahasiswa')
    op.drop_table('krs')
    # ### end Alembic commands ###
