"""empty message

Revision ID: b31075010454
Revises: 4f5ada87142f
Create Date: 2018-07-16 17:02:07.421111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b31075010454'
down_revision = '4f5ada87142f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mahasiswa', sa.Column('password_hash', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mahasiswa', 'password_hash')
    # ### end Alembic commands ###
