"""empty message

Revision ID: c28bfec6b5e0
Revises: 8896b3f5d2e3
Create Date: 2018-07-15 11:14:39.766086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c28bfec6b5e0'
down_revision = '8896b3f5d2e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hash_password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'hash_password')
    # ### end Alembic commands ###
